name: Python CI

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch (or use 'master' depending on your setup)
  pull_request:
    branches:
      - master  # Trigger on pull requests to the master branch

jobs:
  test:
    runs-on: ubuntu-latest  # This uses the latest Ubuntu runner on GitHub Actions

    steps:
      # Check out the code from the repository, to ensure github has access
      # to your files:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # You can specify your desired Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest test_example.py
